# 이 것은 포트에 대한 설정
server:
  port: 88

spring:
  # DB 연동을 위한 설정  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver #cj가 꼭 붙어야 한다.
    url: jdbc:mysql://localhost:3306/memo_210520?serverTimezone=UTC&characterEncoding=UTF-8 # DB를 잘 입력하자 틀리면 나중에 여기와서 찾기 힘들어진다.
    username: root
    password: root # 비밀번호는 공걔가 되니 자주쓰는 걸로 쓰지마자
  
  # 
  mvc:
    # jsp page 연동하기 위한 설정
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    # static 관련된 내용을 넣는 용도임(주로 사진이 였음...)
    static-path-pattern: /static/**
